# Generated by Django 4.1.4 on 2022-12-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_dispaly_name_customer_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
