# Generated by Django 4.1.4 on 2022-12-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
