# Generated by Django 4.1.4 on 2022-12-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_office_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
