# Generated by Django 4.1.4 on 2022-12-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_office_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
