# Generated by Django 4.1.5 on 2023-04-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_office_first_name_office_last_name_office_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
