# Generated by Django 4.1.5 on 2023-04-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('visited_from', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('office_visited_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('is_signed_out', models.BooleanField(default=0, null=True)),
                ('sign_out_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('time_in', models.TimeField(auto_now_add=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('date_visited', models.DateField(auto_now=True, null=True)),
                ('office_visited', models.CharField(blank=True, max_length=200, null=True)),
                ('on_behalf', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
