# Generated by Django 4.1.4 on 2022-12-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='time_in',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='time_out',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
