# Generated by Django 4.1.4 on 2022-12-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_visitor_time_in_visitor_time_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='visitor_from',
            new_name='visited_from',
        ),
        migrations.AddField(
            model_name='visitor',
            name='date_visited',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
