# Generated by Django 4.1.4 on 2022-12-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_rename_visitor_from_visitor_visited_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
