# Generated by Django 4.1.4 on 2022-12-16 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_alter_office_created_on'),
        ('visitor', '0004_visitor_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='office_visited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='office.office'),
        ),
    ]
