# Generated by Django 4.1.4 on 2022-12-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_alter_visitor_office_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='office_visited',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
