# Generated by Django 4.1.4 on 2022-12-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_alter_visitor_office_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
