# Generated by Django 4.1.5 on 2023-01-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0008_rename_national_id_visitor_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_visited',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
