# Generated by Django 4.1.5 on 2023-01-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0009_alter_visitor_date_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='time_in',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
