# Generated by Django 4.1.5 on 2023-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0010_alter_visitor_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='time_in',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
