# Generated by Django 4.1.5 on 2023-04-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0012_visitor_signed_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='signed_out',
            new_name='is_signed_out',
        ),
    ]
