# Generated by Django 4.1.5 on 2023-04-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0013_rename_signed_out_visitor_is_signed_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
