# Generated by Django 4.1.5 on 2023-04-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0015_visitor_office_visited_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='sign_out_code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time_in',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
